pipeline {
    agent any
    stages {
        stage('Check which versions are installed on the node') {
            steps {
               echo "Java version is: "
               sh "java --version"
               echo "Maven version is:"
               sh "mvn --version"
               echo "Python version is:"
               sh "python3 --version"
            }
        }

    }   
}