pipeline {
  agent any
  tools {
  maven "Maven 3.5.0"
  jdk "JDK 9"
  }
  stages {
      stage("Test version") {
          steps {
              sh 'mvn -v' 
          }
      }
  }
//   post {
//     failure {
//       echo 'I will print only on failure'
//     }
//     success {
//       echo 'I will print only on success'
//     }
//     always {
//       echo ‘I will always execute this’
//     }
//   }
}
