pipeline {
    agent any 
    environment {
        HEADHASH = "${GIT_COMMIT.substring(0, 6)}"
    } 
    stages {
        stage('Check Environment') {
            steps {
                sh "ls -la ./feature08/jhipster/ && pwd"
                sh "whoami"
            }
        }
        stage('Build') {
            steps{
              withCredentials([usernamePassword(credentialsId: 'rnikolaev-dockerhub', usernameVariable: 'REGISTRY_CREDS_USR', passwordVariable: 'REGISTRY_CREDS_PSW')]) {
                sh "chmod +x ./feature08/jhipster/mvnw"
                sh "cd ./feature08/jhipster/ && ./mvnw -Pprod clean package jib:build -Djib.to.auth.username=$REGISTRY_CREDS_USR -Djib.to.auth.password=$REGISTRY_CREDS_PSW -Dimage=registry.hub.docker.com/android2e/jhipster:latest -Djib.to.tags=$HEADHASH -DskipTests"
              }
            } 
        }
    }
  post {
    always {
      node ('built-in'){
        sh 'docker ps'
        sh 'docker image ls'
        sh 'docker volume ls'
      }

    }
  }

}