pipeline {
    agent any
    stages {
        stage("Build") {
            steps {          
                sh "pwd"
                sh "ls -la"
                sh "whoami"
                sh "mvn -v" 
            }
        }
    }
}
