pipeline {
    agent {
        docker { image 'node:16.13.1-alpine' }
    }
    stages {
        stage('Test') {
            steps {
                sh 'node --version'
            }
        }
    }
  post {
    always {
      node ('built-in'){
        sh 'docker ps'
        sh 'docker image ls'
        sh 'docker volume ls'
      }

    }
  }
}