pipeline {
    agent {
        docker { image 'node:16.13.1-alpine' }
    }
    stages {
        stage('Test') {
            steps {
                sh 'node --version'
            }
        }
    }
  post {
    always {
      node ('Built-In Node'){
        steps{
          echo '----------------------'
          echo 'CONTAINERS'
          echo '----------------------'
          sh 'docker ps'
          echo '----------------------'
          echo 'IMAGES'
          echo '----------------------'
          sh 'docker image ls'
          echo '----------------------'
          echo 'VOLUMES'
          echo '----------------------'
          sh 'docker volume ls'
        }
      }

    }
  }
}